# Phase 2 — Market Holiday Calendars (editable)
# Dates format: YYYY-MM-DD (local market calendar date)
markets:
  NSE:               # National Stock Exchange (India)
    - "2025-01-01"   # New Year (sample)
    - "2025-01-26"   # Republic Day (sample)
    - "2025-03-14"   # Holi (sample)
    - "2025-08-15"   # Independence Day (sample)
    - "2025-10-02"   # Gandhi Jayanti (sample)
    - "2025-10-20"   # Diwali (sample)
    - "2025-12-25"   # Christmas (sample)
  NYSE:              # New York Stock Exchange (USA)
    - "2025-01-01"   # New Year (sample)
    - "2025-01-20"   # MLK Day (sample)
    - "2025-02-17"   # Presidents' Day (sample)
    - "2025-04-18"   # Good Friday (sample)
    - "2025-05-26"   # Memorial Day (sample)
    - "2025-07-04"   # Independence Day (sample)
    - "2025-09-01"   # Labor Day (sample)
    - "2025-11-27"   # Thanksgiving (sample)
    - "2025-12-25"   # Christmas (sample)
# NOTE: Yeh list placeholders hai. Aap apne official holiday list ke mutabiq update kar dena.
