# Phase 2 — Policy Windows (editable)
# Time windows ko hum **UTC** ya kisi timezone name se parse karte hain.
# Example window:
# - tag: US_CPI
#   tz: "America/New_York"
#   start: "2025-09-10 08:00"
#   end:   "2025-09-10 09:30"

news_freezes:
  - tag: US_FOMC
    tz: "America/New_York"
    start: "2025-09-17 13:30"
    end:   "2025-09-17 15:30"
  - tag: US_CPI
    tz: "America/New_York"
    start: "2025-09-11 08:00"
    end:   "2025-09-11 09:15"
  - tag: RBI_POLICY
    tz: "Asia/Kolkata"
    start: "2025-10-04 09:00"
    end:   "2025-10-04 11:00"

weekly_digest:
  # Digest kab bhejna hai (IST time)
  tz: "Asia/Kolkata"
  weekday: 6          # 0=Mon ... 6=Sun
  hour: 18
  minute: 0
